### ISSUE TITLE
Method getModel not present.

### ISSUE THREAD

**Issue by latheesan-k** [matriphe/larinfo#2] opened 2017-09-13 09:57 UTC
Original question: https://stackoverflow.com/questions/46186587/using-matriphe-larinfo-on-laravel-5-4-project-getting-class-not-found-error/46188265#46188265

When I use the following line:

> $larinfo = Larinfo::getInfo(); // For all info

I get the following error:

![image](https://user-images.githubusercontent.com/6196415/30371319-2a526b60-9872-11e7-950e-09eab6a2ce93.png)

I am on `Windows 7 x64` using XAMPP with PHP 7.1 x86 (`php_com_dotnet` is enabled).

**Comment by matriphe** [comment] 2017-09-14 01:35
Thanks for the report. I haven't tested it in Windows, since I'm using Mac. I will try it in the Windows machine.

**Comment by latheesan-k** [comment] 2017-09-14 08:51
Maybe the issue is with the way you are checking if object exists?

```php
    private function ifExists($object)
    {
        return ! empty($object) ? $object : null;
    }
```

Maybe something like this?

```php
    private function ifExists($object, $method)
    {
        return $object !== null && method_exists($object, $method);
    }
```
Then update all the `$this->ifExists` calls.

**Comment by matriphe** [comment] 2017-09-14 08:55
the problem is in the `linfo/linfo` package. I've make a PR to `linfo/linfo` to accomodate this (https://github.com/jrgp/linfo/pull/67).

the `ifExists` function worked in Linux and Mac, but didn't in Windows (don't know why).

I'm still investigating this. And also, I'm open for a PR.

**Comment by andreaschrist27** [comment] 2018-03-13 12:29
i have this problem

**Comment by matriphe** [comment] 2021-04-04 22:19
Please check the latest release 3.0. I hope it helps. Closing it for now. If you have any issue, you can reopen this.

**Closed by matriphe** 2021-04-04 22:19 UTC
